BITS 32
;TEST_FILE_META_BEGIN
;TEST_TYPE=TEST_F
;TEST_IGNOREFLAGS=FLAG_FPU_C1|FLAG_FPU_PE
;TEST_FILE_META_END

; set up st0 to be PI/2
FLDPI
LEA ESI, [ESP-08]
MOV word [ESI], 0x2
FIDIV word [ESI]

;TEST_BEGIN_RECORDING
FSIN
;TEST_END_RECORDING

