BITS 32
;TEST_FILE_META_BEGIN
;TEST_TYPE=TEST_F
;TEST_IGNOREFLAGS=
;TEST_FILE_META_END
    ; ILD_F64m
    ;TEST_BEGIN_RECORDING
    lea edi, [esp-0x10]
    mov DWORD [edi], 0x00001
    mov DWORD [edi+4], 0x10001
    fild QWORD [edi]
    mov edi, 0x0
    ;TEST_END_RECORDING



