BITS 32
;TEST_FILE_META_BEGIN
;TEST_TYPE=TEST_F
;TEST_IGNOREFLAGS=FLAG_SF|FLAG_ZF|FLAG_AF|FLAG_PF
;TEST_FILE_META_END
    ; IMUL16rr
    mov bx, 0x34
    mov cx, 0x45
    ;TEST_BEGIN_RECORDING
    imul bx, cx
    ;TEST_END_RECORDING

