BITS 32
;TEST_FILE_META_BEGIN
;TEST_TYPE=TEST_F
;TEST_IGNOREFLAGS=FLAG_OF
;TEST_FILE_META_END
    ; ROR32r1
    mov eax, 0x56789
    ;TEST_BEGIN_RECORDING
    ror eax, 0x1   
    ;TEST_END_RECORDING

