BITS 32
;TEST_FILE_META_BEGIN
;TEST_TYPE=TEST_F
;TEST_IGNOREFLAGS=
;TEST_FILE_META_END
    ; SETE
    mov ecx, 0x010
    mov ebx, 0x010
    cmp ecx, ebx
    ;TEST_BEGIN_RECORDING
    sete al
    ;TEST_END_RECORDING 
