BITS 32
;TEST_FILE_META_BEGIN
;TEST_TYPE=TEST_F
;TEST_IGNOREFLAGS=FLAG_AF|FLAG_OF
;TEST_FILE_META_END
    ; SHL16ri
    mov cx, 0x78
    ;TEST_BEGIN_RECORDING
    shl cx, 0x8
    ;TEST_END_RECORDING

