// 
// Tests for generating ABI library functions
// Include all (almost all?) files from /usr/include
//
// TODO: automate running this :)
//

#define _GNU_SOURCE 1
#define _REGEX_RE_COMP
#define _BSD_SOURCE 1

#include <aio.h>
#include <aliases.h>
#include <alloca.h>
#include <argp.h>
#include <argz.h>
#include <ar.h>
#include <arpa/inet.h>
#include <asm/prctl.h>
#include <assert.h>
#include <byteswap.h>
#include <com_err.h>
#include <complex.h>
#include <cpio.h>
#include <crypt.h>
#include <ctype.h>
#include <dirent.h>
#include <dlfcn.h>
#include <elf.h>
#include <endian.h>
#include <envz.h>
#include <err.h>
#include <errno.h>
#include <error.h>
#include <eti.h>
#include <execinfo.h>
#include <fcntl.h>
#include <features.h>
#include <fenv.h>
#include <float.h>
#include <fmtmsg.h>
#include <fnmatch.h>
#include <form.h>
#include <fpu_control.h>
#include <fstab.h>
#include <fts.h>
#include <ftw.h>
#include <gconv.h>
#include <gcrypt.h>
#include <getopt.h>
#include <glob.h>
#include <gnu/libc-version.h>
#include <gnumake.h>
#include <gnu-versions.h>
#include <grp.h>
#include <gshadow.h>
#include <gssapi.h>
#include <hwloc.h>
#include <iconv.h>
#include <ifaddrs.h>
#include <inttypes.h>
#include <iso646.h>
#include <kdb.h>
#include <krb5.h>
#include <langinfo.h>
#include <lastlog.h>
#include <lber.h>
#include <lber_types.h>
#include <ldap_cdefs.h>
#include <ldap_features.h>
#include <ldap.h>
#include <ldap_schema.h>
#include <ldap_utf8.h>
#include <ldif.h>
#include <libgen.h>
#include <libintl.h>
#include <libio.h>
#include <libsync.h>
#include <limits.h>
#include <link.h>
#include <locale.h>
#include <lz4frame.h>
#include <lz4.h>
#include <lz4hc.h>
#include <lzma.h>
#include <magic.h>
#include <malloc.h>
#include <math.h>
#include <mcheck.h>
#include <memory.h>
#include <menu.h>
#include <mntent.h>
#include <monetary.h>
#include <mpc.h>
#include <mpf2mpfr.h>
#include <mpfr.h>
#include <mqueue.h>
#include <nc_tparm.h>
#include <ncurses_dll.h>
#include <ncurses.h>
#include <netdb.h>
#include <net/if.h>
#include <netinet/ether.h>
#include <netinet/icmp6.h>
#include <netinet/if_ether.h>
#include <netinet/if_fddi.h>
#include <netinet/if_tr.h>
#include <netinet/igmp.h>
#include <netinet/in.h>
#include <netinet/in_systm.h>
#include <netinet/ip6.h>
#include <netinet/ip.h>
#include <netinet/ip_icmp.h>
#include <netinet/tcp.h>
#include <netinet/udp.h>
#include <nl_types.h>
#include <nss.h>
#include <numa.h>
#include <obstack.h>
#include <panel.h>
#include <paths.h>
#include <poll.h>
#include <printf.h>
#include <profile.h>
#include <pthread.h>
#include <pty.h>
#include <pwd.h>
#include <re_comp.h>
#include <regex.h>
#include <resolv.h>
#include <rpc/auth_des.h>
#include <rpc/auth.h>
#include <rpc/auth_unix.h>
#include <rpc/clnt.h>
#include <rpc/des_crypt.h>
#include <rpc/key_prot.h>
#include <rpc/netdb.h>
#include <rpc/pmap_clnt.h>
#include <rpc/pmap_prot.h>
#include <rpc/pmap_rmt.h>
#include <rpc/rpc_des.h>
#include <rpc/rpc.h>
#include <rpc/rpc_msg.h>
#include <rpc/svc_auth.h>
#include <rpc/svc.h>
#include <rpc/types.h>
#include <rpc/xdr.h>
#include <sched.h>
#include <search.h>
#include <semaphore.h>
#include <setjmp.h>
#include <sgtty.h>
#include <shadow.h>
#include <signal.h>
#include <spawn.h>
#include <stab.h>
#include <stdarg.h>
#include <stdbool.h>
#include <stdc-predef.h>
#include <stddef.h>
#include <stdint.h>
#include <stdio_ext.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <strings.h>
#include <stropts.h>
#include <sudo_plugin.h>
#include <sys/acct.h>
#include <sys/acl.h>
#include <sys/auxv.h>
#include <sys/bitypes.h>
#include <syscall.h>
#include <sys/capability.h>
#include <sys/cdefs.h>
#include <sys/debugreg.h>
#include <sys/dir.h>
#include <sys/epoll.h>
#include <sys/errno.h>
#include <sys/eventfd.h>
#include <sysexits.h>
#include <sys/fanotify.h>
#include <sys/fcntl.h>
#include <sys/file.h>
#include <sys/fsuid.h>
#include <sys/gmon.h>
#include <sys/gmon_out.h>
#include <sys/inotify.h>
#include <sys/ioctl.h>
#include <sys/io.h>
#include <sys/ipc.h>
#include <sys/kd.h>
#include <sys/klog.h>
#include <syslog.h>
#include <sys/mman.h>
#include <sys/mount.h>
#include <sys/msg.h>
#include <sys/mtio.h>
#include <sys/param.h>
#include <sys/pci.h>
#include <sys/perm.h>
#include <sys/personality.h>
#include <sys/poll.h>
#include <sys/prctl.h>
#include <sys/procfs.h>
#include <sys/profil.h>
#include <sys/ptrace.h>
#include <sys/queue.h>
#include <sys/quota.h>
#include <sys/raw.h>
#include <sys/reboot.h>
#include <sys/reg.h>
#include <sys/resource.h>
#include <sys/select.h>
#include <sys/sem.h>
#include <sys/sendfile.h>
#include <sys/shm.h>
#include <sys/signalfd.h>
#include <sys/signal.h>
#include <sys/socket.h>
#include <sys/socketvar.h>
#include <sys/soundcard.h>
#include <sys/statfs.h>
#include <sys/stat.h>
#include <sys/statvfs.h>
#include <sys/stropts.h>
#include <sys/swap.h>
#include <sys/syscall.h>
#include <sys/sysctl.h>
#include <sys/sysinfo.h>
#include <sys/syslog.h>
#include <sys/sysmacros.h>
#include <sys/termios.h>
#include <sys/timeb.h>
#include <sys/time.h>
#include <sys/timerfd.h>
#include <sys/times.h>
#include <sys/timex.h>
#include <sys/ttychars.h>
#include <sys/ttydefaults.h>
#include <sys/types.h>
#include <sys/ucontext.h>
#include <sys/uio.h>
#include <sys/ultrasound.h>
#include <sys/un.h>
#include <sys/unistd.h>
#include <sys/user.h>
#include <sys/ustat.h>
#include <sys/utsname.h>
#include <sys/vfs.h>
#include <sys/vlimit.h>
#include <sys/vt.h>
#include <sys/vtimes.h>
#include <sys/wait.h>
#include <sys/xattr.h>
#include <tar.h>
#include <tcpd.h>
#include <termcap.h>
#include <term.h>
#include <termio.h>
#include <termios.h>
#include <tgmath.h>
#include <thread_db.h>
#include <time.h>
#include <ttyent.h>
#include <uchar.h>
#include <ucontext.h>
#include <ulimit.h>
#include <unbound.h>
#include <unctrl.h>
#include <unistd.h>
#include <ustat.h>
#include <utime.h>
#include <utmp.h>
#include <utmpx.h>
#include <uv-errno.h>
#include <uv.h>
#include <uv-linux.h>
#include <uv-threadpool.h>
#include <uv-unix.h>
#include <uv-version.h>
#include <values.h>
#include <wait.h>
#include <wchar.h>
#include <wctype.h>
#include <wordexp.h>
#include <xlocale.h>
#include <xtables.h>
#include <xtables-version.h>
#include <zconf.h>

