all: test tests.out

tests.out:
	pin -t $$PWD/../valTool/obj-intel64/val.so -- ./test

test: test_a.o test.o
	cc -m64 -o test test.o test_a.o

test_a.o: test_a.asm
	nasm -f macho64 -o test_a.o test_a.asm

test.o: test.c
	cc -m64 -c -o test.o test.c


clean:
	rm -f *.o tests.out
