tests.out:
	pin -t $$PWD/../valTool/obj-ia32/val.so -- ./test

test: test_a.o test.o
	gcc -m32 -o test test.o test_a.o

test_a.o: test_a.asm
	nasm -f macho -o test_a.o test_a.asm

test.o: test.c
	gcc -m32 -c -o test.o test.c

all: test tests.out
