BITS 64
;TEST_FILE_META_BEGIN
;TEST_TYPE=TEST_F
;TEST_IGNOREFLAGS=
;TEST_FILE_META_END
    ; Adc64RR
    mov rax, 0xdead1234abcd
    mov rdx, 0xdead2345bcde
    ;TEST_BEGIN_RECORDING
    adc rax, rdx
    ;TEST_END_RECORDING

