BITS 64
;TEST_FILE_META_BEGIN
;TEST_TYPE=TEST_F
;TEST_IGNOREFLAGS=
;TEST_FILE_META_END
    ; ADD32rr
    mov ecx, 0x7fffffff
    mov edx, 0x6ffeeeee
    ;TEST_BEGIN_RECORDING
    add ecx, edx
    ;TEST_END_RECORDING

