BITS 64
;TEST_FILE_META_BEGIN
;TEST_TYPE=TEST_F
;TEST_IGNOREFLAGS=FLAG_AF
;TEST_FILE_META_END
    ; AND8rr
    mov ch, 0xa
    mov dh, 0xe8
    ;TEST_BEGIN_RECORDING
    and ch, dh
    ;TEST_END_RECORDING

