BITS 64
;TEST_FILE_META_BEGIN
;TEST_TYPE=TEST_F
;TEST_IGNOREFLAGS=FLAG_CF|FLAG_OF|FLAG_PF|FLAG_SF|FLAG_AF
;TEST_FILE_META_END
    ; BSR64rr; test special case zero source op
    mov rax, 0x00000000
    ;TEST_BEGIN_RECORDING
    bsr rbx, rax
    ;TEST_END_RECORDING
