BITS 64
;TEST_FILE_META_BEGIN
;TEST_TYPE=TEST_F
;TEST_IGNOREFLAGS=
;TEST_FILE_META_END
    ; Cmova32RR
    mov eax, 0x3333
    mov ecx, 0x4444
    ;TEST_BEGIN_RECORDING
    cmova eax, ecx
    ;TEST_END_RECORDING

