BITS 64
;TEST_FILE_META_BEGIN
;TEST_TYPE=TEST_F
;TEST_IGNOREFLAGS=
;TEST_FILE_META_END
    ; CMP16mi
    ;TEST_BEGIN_RECORDING
    lea rax, [rsp-0x4]
    mov DWORD [rax], 0x200
    cmp WORD [rax], 0x222
    mov eax, 0x0
    ;TEST_END_RECORDING

