BITS 64
;TEST_FILE_META_BEGIN
;TEST_TYPE=TEST_F
;TEST_IGNOREFLAGS=
;TEST_FILE_META_END
    ; CMP32rr
    mov ecx, 0x4
    mov edx, 0x2
    ;TEST_BEGIN_RECORDING
    cmp ecx, edx
    ;TEST_END_RECORDING

