BITS 64
;TEST_FILE_META_BEGIN
;TEST_TYPE=TEST_F
;TEST_IGNOREFLAGS=
;TEST_FILE_META_END
    ; CMPXCHG16r
    mov bx, 0x667
    mov bp, 0x888
    ;TEST_BEGIN_RECORDING
    cmpxchg bx, bp
    ;TEST_END_RECORDING

