BITS 64
;TEST_FILE_META_BEGIN
;TEST_TYPE=TEST_F
;TEST_IGNOREFLAGS=FLAG_CF|FLAG_OF|FLAG_SF|FLAG_ZF|FLAG_AF|FLAG_PF
;TEST_FILE_META_END
    ; IDIV32r
    mov rax, 0x4444
    mov rbx, 0x4
    mov rdx, 0x1
    ;TEST_BEGIN_RECORDING
    idiv rbx
    ;TEST_END_RECORDING

