BITS 64
;TEST_FILE_META_BEGIN
;TEST_TYPE=TEST_F
;TEST_IGNOREFLAGS=FLAG_CF|FLAG_OF|FLAG_SF|FLAG_ZF|FLAG_AF|FLAG_PF
;TEST_FILE_META_END
    ; IDIV32r
    mov eax, 0x4444
    mov ebx, 0x4
    mov edx, 0x1
    ;TEST_BEGIN_RECORDING
    idiv ebx
    ;TEST_END_RECORDING

