BITS 64
;TEST_FILE_META_BEGIN
;TEST_TYPE=TEST_F
;TEST_IGNOREFLAGS=
;TEST_FILE_META_END
    ; ILD_F64m
    ;TEST_BEGIN_RECORDING
    lea rdi, [rsp-0x10]
    mov DWORD [rdi], 0x00001
    mov DWORD [rdi+4], 0x10001
    fild QWORD [rdi]
    mov rdi, 0x0
    ;TEST_END_RECORDING



