BITS 64
;TEST_FILE_META_BEGIN
;TEST_TYPE=TEST_F
;TEST_IGNOREFLAGS=FLAG_SF|FLAG_ZF|FLAG_AF|FLAG_PF
;TEST_FILE_META_END
    ; IMUL64rr
    mov ebx, 0x20000
    mov ecx, 0x34
    ;TEST_BEGIN_RECORDING
    imul ebx, ecx
    ;TEST_END_RECORDING

