BITS 64
;TEST_FILE_META_BEGIN
;TEST_TYPE=TEST_F
;TEST_IGNOREFLAGS=FLAG_SF|FLAG_ZF|FLAG_AF|FLAG_PF
;TEST_FILE_META_END
    ; IMUL64rri8
    mov ebx, 0x20000
    mov ecx, 0x34343434
    ;TEST_BEGIN_RECORDING
    imul ebx, ecx, 0xb
    ;TEST_END_RECORDING

