BITS 64
;TEST_FILE_META_BEGIN
;TEST_TYPE=TEST_F
;TEST_IGNOREFLAGS=FLAG_SF|FLAG_ZF|FLAG_AF|FLAG_PF
;TEST_FILE_META_END
    ; IMUL16r
    mov ax, 0x32
    mov bx, 0xb
    ;TEST_BEGIN_RECORDING
    imul bx
    ;TEST_END_RECORDING

