BITS 64
;TEST_FILE_META_BEGIN
;TEST_TYPE=TEST_F
;TEST_IGNOREFLAGS=
;TEST_FILE_META_END
    ; Lea32R2
    mov eax, 0x515
    mov edx, 0x30
    ;TEST_BEGIN_RECORDING
    lea ecx, [eax+edx*0x4]
    ;TEST_END_RECORDING

