BITS 64
;TEST_FILE_META_BEGIN
;TEST_TYPE=TEST_F
;TEST_IGNOREFLAGS=
;TEST_FILE_META_END
    ; MOVSX16rr8
    mov bx, 0x3000
    mov bl, 0x35
    ;TEST_BEGIN_RECORDING
    movsx bx, bl
    ;TEST_END_RECORDING

