BITS 64
;TEST_FILE_META_BEGIN
;TEST_TYPE=TEST_F
;TEST_IGNOREFLAGS=
;TEST_FILE_META_END
    ; MOVSX32rr8
    mov eax, 0x55555
    mov ah, 0x3
    ;TEST_BEGIN_RECORDING
    movsx eax, ah
    ;TEST_END_RECORDING

