BITS 64
;TEST_FILE_META_BEGIN
;TEST_TYPE=TEST_F
;TEST_IGNOREFLAGS=FLAG_FPU_C1|FLAG_FPU_PE
;TEST_FILE_META_END

; set up st0 and st1 to be pi
FLDPI
FLDPI
;TEST_BEGIN_RECORDING
FMUL st0, st1
;TEST_END_RECORDING

