BITS 64
;TEST_FILE_META_BEGIN
;TEST_TYPE=TEST_F
;TEST_IGNOREFLAGS=FLAG_AF|FLAG_OF
;TEST_FILE_META_END
    ; Sar32RI1
    mov ebx, 0x56
    ;TEST_BEGIN_RECORDING
    sar ebx, 0x3
    ;TEST_END_RECORDING

