BITS 64
;TEST_FILE_META_BEGIN
;TEST_TYPE=TEST_F
;TEST_IGNOREFLAGS=FLAG_AF|FLAG_OF
;TEST_FILE_META_END
    ; Shl32RI
    mov eax, 0x1
    ;TEST_BEGIN_RECORDING
    shl eax, 0xa
    ;TEST_END_RECORDING

