BITS 64
;TEST_FILE_META_BEGIN
;TEST_TYPE=TEST_F
;TEST_IGNOREFLAGS=FLAG_AF|FLAG_OF
;TEST_FILE_META_END
    ; SHL8rCL
    mov bh, 0xa
    mov cl, 0x3
    ;TEST_BEGIN_RECORDING
    shl bh, cl
    ;TEST_END_RECORDING

