BITS 64
;TEST_FILE_META_BEGIN
;TEST_TYPE=TEST_F
;TEST_IGNOREFLAGS=FLAG_AF|FLAG_OF
;TEST_FILE_META_END
    ; SHR16r1
    mov ax, 0xe45
    ;TEST_BEGIN_RECORDING
    shr ax, 0x1
    ;TEST_END_RECORDING

