BITS 64
;TEST_FILE_META_BEGIN
;TEST_TYPE=TEST_F
;TEST_IGNOREFLAGS=FLAG_AF|FLAG_OF
;TEST_FILE_META_END
    ; SHR32rCL
    mov ebx, 0x654
    mov cl, 0x5
    ;TEST_BEGIN_RECORDING
    shr ebx, cl
    ;TEST_END_RECORDING

