BITS 64
;TEST_FILE_META_BEGIN
;TEST_TYPE=TEST_F
;TEST_IGNOREFLAGS=FLAG_AF|FLAG_OF
;TEST_FILE_META_END
    ; SHR8rCL
    mov bh, 0xe
    mov cl, 0x2
    ;TEST_BEGIN_RECORDING
    shr bh, cl
    ;TEST_END_RECORDING

