BITS 64
;TEST_FILE_META_BEGIN
;TEST_TYPE=TEST_F
;TEST_IGNOREFLAGS=FLAG_FPU_IE
;TEST_FILE_META_END
    ; ST_F32m
    FLD1
    ;TEST_BEGIN_RECORDING
    lea rdi, [rsp-0x4]
    fst DWORD [rdi]
    mov eax, [rdi]
    mov edi, 0x0
    ;TEST_END_RECORDING

