BITS 64
;TEST_FILE_META_BEGIN
;TEST_TYPE=TEST_F
;TEST_IGNOREFLAGS=FLAG_AF
;TEST_FILE_META_END
    ; TEST8rr
    mov ch, 0x2
    mov dh, 0x3
    ;TEST_BEGIN_RECORDING
    test ch, dh
    ;TEST_END_RECORDING

