BITS 64
;TEST_FILE_META_BEGIN
;TEST_TYPE=TEST_F
;TEST_IGNOREFLAGS=FLAG_AF
;TEST_FILE_META_END
    ; Test32RR2
    mov edi, 0x8
    mov eax, 0x12
    ;TEST_BEGIN_RECORDING
    test edi, eax
    ;TEST_END_RECORDING

