BITS 64
;TEST_FILE_META_BEGIN
;TEST_TYPE=TEST_F
;TEST_IGNOREFLAGS=FLAG_AF
;TEST_FILE_META_END
    ; TEST32i32
    mov eax, 0x7
    ;TEST_BEGIN_RECORDING
    test eax, 0x6fffffff
    ;TEST_END_RECORDING

