BITS 64
;TEST_FILE_META_BEGIN
;TEST_TYPE=TEST_F
;TEST_IGNOREFLAGS=
;TEST_FILE_META_END
    ; XADD32rr
    mov ebx, 0xb46767
    mov ecx, 0xa57877
    ;TEST_BEGIN_RECORDING
    xadd ebx, ecx
    ;TEST_END_RECORDING

