BITS 64
;TEST_FILE_META_BEGIN
;TEST_TYPE=TEST_F
;TEST_IGNOREFLAGS=
;TEST_FILE_META_END
    ; Xadd16RR
    mov ax, 0x6824
    mov dx, 0x1479
    ;TEST_BEGIN_RECORDING
    xadd ax, dx
    ;TEST_END_RECORDING

