BITS 64
;TEST_FILE_META_BEGIN
;TEST_TYPE=TEST_F
;TEST_IGNOREFLAGS=
;TEST_FILE_META_END
    ; XCHG32rr
    mov ebx, 0x120
    mov ecx, 0x122
    ;TEST_BEGIN_RECORDING
    xchg ebx, ecx
    ;TEST_END_RECORDING

