BITS 64
;TEST_FILE_META_BEGIN
;TEST_TYPE=TEST_F
;TEST_IGNOREFLAGS=
;TEST_FILE_META_END
    ; XCHG16rr
    mov bx, 0xc
    mov dx, 0xd
    ;TEST_BEGIN_RECORDING
    xchg bx, dx
    ;TEST_END_RECORDING

