BITS 64
;TEST_FILE_META_BEGIN
;TEST_TYPE=TEST_F
;TEST_IGNOREFLAGS=
;TEST_FILE_META_END
    ; XCHG16ar
    mov ax, 0x6
    mov bx, 0x7
    ;TEST_BEGIN_RECORDING
    xchg ax, bx
    ;TEST_END_RECORDING

