BITS 32
;TEST_FILE_META_BEGIN
;TEST_TYPE=TEST_F
;TEST_IGNOREFLAGS=FLAG_AF
;TEST_FILE_META_END
    ; AND32i32
    mov eax, 0x7
    ;TEST_BEGIN_RECORDING
    and eax, 0x6fffffff
    ;TEST_END_RECORDING

