BITS 32
;TEST_FILE_META_BEGIN
;TEST_TYPE=TEST_F
;TEST_IGNOREFLAGS=FLAG_AF
;TEST_FILE_META_END
    ; AND8mi
    ;TEST_BEGIN_RECORDING
    lea ebx, [esp-0x4]
    mov DWORD [ebx], 0x55
    and BYTE [ebx], 0x44
    mov ebx, 0x0
    ;TEST_END_RECORDING

