BITS 32
;TEST_FILE_META_BEGIN
;TEST_TYPE=TEST_F
;TEST_IGNOREFLAGS=
;TEST_FILE_META_END
    ; Cmp32RR2
    mov eax, 0x17
    mov ebx, 0x3
    ;TEST_BEGIN_RECORDING
    cmp eax, ebx
    ;TEST_END_RECORDING

