BITS 32
;TEST_FILE_META_BEGIN
;TEST_TYPE=TEST_F
;TEST_IGNOREFLAGS=
;TEST_FILE_META_END
    ; Cmpxch16RR
    mov ax, 0x6824
    mov dx, 0x6824
    mov cx, 0x1479
    ;TEST_BEGIN_RECORDING
    cmpxchg dx, cx
    ;TEST_END_RECORDING

