BITS 32
;TEST_FILE_META_BEGIN
;TEST_TYPE=TEST_F
;TEST_IGNOREFLAGS=
;TEST_FILE_META_END


;TEST_BEGIN_RECORDING
lea edi, [esp-0xc]
mov word [edi], 0x10
FILD word [edi]
FILD word [edi]
FYL2X ;st1 = 16 * log2(16)
;TEST_END_RECORDING

