BITS 32
;TEST_FILE_META_BEGIN
;TEST_TYPE=TEST_F
;TEST_IGNOREFLAGS=FLAG_SF|FLAG_ZF|FLAG_AF|FLAG_PF
;TEST_FILE_META_END
    ; IMUL32r
    mov eax, 0x323
    mov ebx, 0xbbb
    ;TEST_BEGIN_RECORDING
    imul ebx
    ;TEST_END_RECORDING

