BITS 32
;TEST_FILE_META_BEGIN
;TEST_TYPE=TEST_F
;TEST_IGNOREFLAGS=
;TEST_FILE_META_END
    ; LEA16r
    mov cx, 0x15
    mov edx, 0x8
    ;TEST_BEGIN_RECORDING
    lea cx, [edx-0x444]
    ;TEST_END_RECORDING

