BITS 32
;TEST_FILE_META_BEGIN
;TEST_TYPE=TEST_F
;TEST_IGNOREFLAGS=
;TEST_FILE_META_END
    ; MOVSX32rr16
    mov eax, 0x55555
    mov ax, 0x3333
    ;TEST_BEGIN_RECORDING
    movsx eax, ax
    ;TEST_END_RECORDING

