BITS 32
;TEST_FILE_META_BEGIN
;TEST_TYPE=TEST_F
;TEST_IGNOREFLAGS=
;TEST_FILE_META_END
    ; POP32r
    mov ecx, 0x7777
    mov edi, 0x0
    ;TEST_BEGIN_RECORDING
    push ecx
    pop edi
    ;TEST_END_RECORDING

