BITS 32
;TEST_FILE_META_BEGIN
;TEST_TYPE=TEST_F
;TEST_IGNOREFLAGS=
;TEST_FILE_META_END
    ; SBB32rr
    mov ecx, 0x0
    mov edx, 0x1
    ;TEST_BEGIN_RECORDING
    sbb ecx, edx
    ;TEST_END_RECORDING

