BITS 32
;TEST_FILE_META_BEGIN
;TEST_TYPE=TEST_F
;TEST_IGNOREFLAGS=
;TEST_FILE_META_END
    ; Sbb32RR1
    mov ecx, 0x1892
    mov edx, 0x4
    ;TEST_BEGIN_RECORDING
    sbb edx, ecx
    ;TEST_END_RECORDING

