BITS 32
;TEST_FILE_META_BEGIN
;TEST_TYPE=TEST_F
;TEST_IGNOREFLAGS=FLAG_AF|FLAG_OF
;TEST_FILE_META_END
    ; SHR16ri
    mov cx, 0x987
    ;TEST_BEGIN_RECORDING
    shr cx, 0x8
    ;TEST_END_RECORDING

