BITS 32
;TEST_FILE_META_BEGIN
;TEST_TYPE=TEST_F
;TEST_IGNOREFLAGS=FLAG_AF|FLAG_OF
;TEST_FILE_META_END
    ; SHR32r1
    mov eax, 0x444444
    ;TEST_BEGIN_RECORDING
    shr eax, 0x1
    ;TEST_END_RECORDING

