BITS 32
;TEST_FILE_META_BEGIN
;TEST_TYPE=TEST_F
;TEST_IGNOREFLAGS=
;TEST_FILE_META_END
    ; Sub32RR
    mov eax, 0x1
    mov ebx, 0x2
    ;TEST_BEGIN_RECORDING
    sub ebx, eax
    ;TEST_END_RECORDING

