BITS 32
;TEST_FILE_META_BEGIN
;TEST_TYPE=TEST_F
;TEST_IGNOREFLAGS=
;TEST_FILE_META_END
    ; XCHG32ar
    mov eax, 0x20
    mov ebx, 0x30
    ;TEST_BEGIN_RECORDING
    xchg eax, ebx
    ;TEST_END_RECORDING

