BITS 32
;TEST_FILE_META_BEGIN
;TEST_TYPE=TEST_F
;TEST_IGNOREFLAGS=FLAG_AF
;TEST_FILE_META_END
    ; XOR16rr
    mov cx, 0x2
    mov dx, 0x3
    ;TEST_BEGIN_RECORDING
    xor cx, dx
    ;TEST_END_RECORDING

