BITS 32
;TEST_FILE_META_BEGIN
;TEST_TYPE=TEST_F
;TEST_IGNOREFLAGS=FLAG_AF
;TEST_FILE_META_END
    ; XOR32i32
    mov eax, 0x12
    ;TEST_BEGIN_RECORDING
    xor eax, 0x6fffffff
    ;TEST_END_RECORDING

