#ensure PIN_HOME is set using Windows-style paths;
#e.g.: C:\pin

all: tests.out

.IGNORE: tests.out
tests.out: test
	cmd.exe /c "${PIN_HOME}\pin.bat -t ..\valTool\obj-ia32\val.dll -- test.exe"

test: test_a.obj test.obj
	gcc -o test test.obj test_a.obj

test_a.obj: test_a.asm
	nasm --prefix _ -f win -o test_a.obj test_a.asm

test.obj: test.c
	gcc -m32 -c -o test.obj test.c

.IGNORE: clean
clean:
	rm -f *.obj tests.out
