BITS 32
;TEST_FILE_META_BEGIN
;TEST_TYPE=TEST_F
;TEST_IGNOREFLAGS=FLAG_AF|FLAG_OF|FLAG_CF
;TEST_FILE_META_END
    ; AAM8i8
    mov al, 0x22
    mov bl, 0x6
    ;TEST_BEGIN_RECORDING
    aam 0xa
    ;TEST_END_RECORDING

