BITS 32
;TEST_FILE_META_BEGIN
;TEST_TYPE=TEST_F
;TEST_IGNOREFLAGS=
;TEST_FILE_META_END
    ; ADC16rr
    mov cx, 0xabc
    mov dx, 0xdef
    ;TEST_BEGIN_RECORDING
    adc cx, dx
    ;TEST_END_RECORDING

