BITS 32
;TEST_FILE_META_BEGIN
;TEST_TYPE=TEST_F
;TEST_IGNOREFLAGS=FLAG_CF|FLAG_OF|FLAG_SF|FLAG_ZF|FLAG_AF|FLAG_PF
;TEST_FILE_META_END
    ; IDIV16r
    mov ax, 0xaa
    mov bx, 0x4
    mov dx, 0x1
    ;TEST_BEGIN_RECORDING
    idiv bx
    ;TEST_END_RECORDING

