BITS 32
;TEST_FILE_META_BEGIN
;TEST_TYPE=TEST_F
;TEST_IGNOREFLAGS=
;TEST_FILE_META_END
    ; Lea32R1
    mov eax, 0x21
    mov edi, 0x8
    ;TEST_BEGIN_RECORDING
    lea eax, [eax+edi+0x1]
    ;TEST_END_RECORDING

