BITS 32
;TEST_FILE_META_BEGIN
;TEST_TYPE=TEST_F
;TEST_IGNOREFLAGS=
;TEST_FILE_META_END
    ; MovZx32RR16
    mov eax, 0x18
    mov ebx, 0
    ;TEST_BEGIN_RECORDING
    movzx ebx, ax
    ;TEST_END_RECORDING

