BITS 32
;TEST_FILE_META_BEGIN
;TEST_TYPE=TEST_F
;TEST_IGNOREFLAGS=FLAG_SF|FLAG_ZF|FLAG_AF|FLAG_PF
;TEST_FILE_META_END
    ; MUL8r
    mov al, 0xFF
    mov cl, 0xCC
    ;TEST_BEGIN_RECORDING
    mul cl
    ;TEST_END_RECORDING
