BITS 32
;TEST_FILE_META_BEGIN
;TEST_TYPE=TEST_F
;TEST_IGNOREFLAGS=
;TEST_FILE_META_END
    ; PushPopR
    mov eax, 0x88
    mov edi, 0x0
    ;TEST_BEGIN_RECORDING
    push eax
    pop edi
    ;TEST_END_RECORDING

