BITS 32
;TEST_FILE_META_BEGIN
;TEST_TYPE=TEST_F
;TEST_IGNOREFLAGS=
;TEST_FILE_META_END
    ; SETNEr
    mov ecx, 0x5
    mov ebx, 0xa
    cmp ecx, ebx
    ;TEST_BEGIN_RECORDING
    setne al
    ;TEST_END_RECORDING
