BITS 32
;TEST_FILE_META_BEGIN
;TEST_TYPE=TEST_F
;TEST_IGNOREFLAGS=FLAG_AF|FLAG_OF
;TEST_FILE_META_END
    ; SHLD32rrCL
    mov cl, 0x1
    mov eax, 0x5dc
    mov ebx, 0x3ca
    ;TEST_BEGIN_RECORDING
    shld ebx, eax, cl
    ;TEST_END_RECORDING

