BITS 32
;TEST_FILE_META_BEGIN
;TEST_TYPE=TEST_F
;TEST_IGNOREFLAGS=FLAG_FPU_C1|FLAG_FPU_PE
;TEST_FILE_META_END

FLDPI
;TEST_BEGIN_RECORDING
lea edi, [esp-0xc]
FST dword [edi]
FSUB dword [edi]
mov edi, 0
;TEST_END_RECORDING

