BITS 32
;TEST_FILE_META_BEGIN
;TEST_TYPE=TEST_F
;TEST_IGNOREFLAGS=FLAG_FPU_PE|FLAG_FPU_C1
;TEST_FILE_META_END

; set up st0 to be 1.0
FLD1
FLDPI
;TEST_BEGIN_RECORDING
lea edi, [esp-0xc]
FSTP qword [edi]
FSUB qword [edi]
mov edi, 0
;TEST_END_RECORDING
