BITS 32
;TEST_FILE_META_BEGIN
;TEST_TYPE=TEST_F
;TEST_IGNOREFLAGS=
;TEST_FILE_META_END
    ; XADD8rr
    mov al, 0x45
    mov bl, 0x56
    ;TEST_BEGIN_RECORDING
    xadd al, bl
    ;TEST_END_RECORDING

