LLVM_PATH=$(<./LLVM_PATH)
CFG_TO_BC_PATH=$(<./CFG_TO_BC_PATH)
BIN_DESCEND_PATH=$(<./BIN_DESCEND_PATH)
IDA_PATH=$(<./IDA_PATH)
GET_CFG_PY=${BIN_DESCEND_PATH}/get_cfg.py
STD_DEFS="../std_defs/std_defs.txt"
CC=gcc
